version: '3'
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server2022
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  web:
    build: ./FrontEnd/
    container_name: car-web
    ports: 
      - "80:80"
  api:
    build: ./BackEnd/
    container_name: car-api
    ports: 
      - "5000:80"
