version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Aa123456!"
    ports:
      - "1433:1433"
  api:
    build: ./FrontEnd/Dockerfile
    ports: 
      - "8080:80"
  web:
    build: ./BackEnd/Dockerfile
    ports: 
      - "80:80"