apiVersion: v1
kind: Service
metadata:
  name: sql-server
  labels:
    app: car-web-sql
spec:
  ports:
    - port: 1433
  selector:
    app: car-web-sql
    tier: mssql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: car-web-sql
  labels:
    app: car-web-sql
spec:
  selector:
    matchLabels:
      app: car-web-sql
      tier: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: car-web-sql
        tier: mssql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: car-web-sql
        image: santospardos/sanvalero:car-sql2022
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
